const data = {
  external_visitors: [
    {
      date: "01/01/2021",
      visitor_id: "0001",
      status: "Scheduled",
      extended_hrs: 1,
    },
    {
      date: "01/02/2021",
      visitor_id: "0002",
      status: "Currently Inside",
      extended_hrs: 2,
    },
    {
      date: "01/03/2021",
      visitor_id: "0003",
      status: "Scheduled",
      extended_hrs: 3,
    },
    {
      date: "01/04/2021",
      visitor_id: "0004",
      status: "Currently Inside",
      extended_hrs: 4,
    },
    {
      date: "01/05/2021",
      visitor_id: "0005",
      status: "Scheduled",
      extended_hrs: 5,
    },
    {
      date: "01/06/2021",
      visitor_id: "0006",
      status: "Currently Inside",
      extended_hrs: 6,
    },
    {
      date: "01/07/2021",
      visitor_id: "0007",
      status: "Scheduled",
      extended_hrs: 7,
    },
    {
      date: "01/08/2021",
      visitor_id: "0008",
      status: "Currently Inside",
      extended_hrs: 8,
    },
    {
      date: "01/09/2021",
      visitor_id: "0009",
      status: "Scheduled",
      extended_hrs: 9,
    },
    {
      date: "01/10/2021",
      visitor_id: "0010",
      status: "Currently Inside",
      extended_hrs: 10,
    },
    {
      date: "01/11/2021",
      visitor_id: "0011",
      status: "Scheduled",
      extended_hrs: 11,
    },
    {
      date: "01/12/2021",
      visitor_id: "0012",
      status: "Currently Inside",
      extended_hrs: 12,
    },
    {
      date: "01/13/2021",
      visitor_id: "0013",
      status: "Scheduled",
      extended_hrs: 13,
    },
    {
      date: "01/14/2021",
      visitor_id: "0014",
      status: "Currently Inside",
      extended_hrs: 14,
    },
    {
      date: "01/15/2021",
      visitor_id: "0015",
      status: "Scheduled",
      extended_hrs: 15,
    },
    {
      date: "01/16/2021",
      visitor_id: "0016",
      status: "Currently Inside",
      extended_hrs: 16,
    },
    {
      date: "01/17/2021",
      visitor_id: "0017",
      status: "Scheduled",
      extended_hrs: 17,
    },
    {
      date: "01/18/2021",
      visitor_id: "0018",
      status: "Currently Inside",
      extended_hrs: 18,
    },
    {
      date: "01/19/2021",
      visitor_id: "0019",
      status: "Scheduled",
      extended_hrs: 19,
    },
  ],
  work_order_schedules: [
    {
      date: "01/01/2021",
      wo_id: "001",
      status: "Scheduled",
    },
    {
      date: "01/02/2021",
      wo_id: "002",
      status: "Not Assigned",
    },
    {
      date: "01/03/2021",
      wo_id: "003",
      status: "Escalated L1",
    },
    {
      date: "01/04/2021",
      wo_id: "004",
      status: "Escalated L2",
    },
    {
      date: "01/05/2021",
      wo_id: "005",
      status: "Escalated L3",
    },
    {
      date: "01/06/2021",
      wo_id: "006",
      status: "Scheduled",
    },
    {
      date: "01/07/2021",
      wo_id: "007",
      status: "Not Assigned",
    },
    {
      date: "01/08/2021",
      wo_id: "008",
      status: "Escalated L4",
    },
    {
      date: "01/09/2021",
      wo_id: "009",
      status: "Escalated L5",
    },
    {
      date: "01/10/2021",
      wo_id: "010",
      status: "Escalated L6",
    },
    {
      date: "01/11/2021",
      wo_id: "011",
      status: "Scheduled",
    },
    {
      date: "01/12/2021",
      wo_id: "012",
      status: "Not Assigned",
    },
    {
      date: "01/13/2021",
      wo_id: "013",
      status: "Escalated L7",
    },
    {
      date: "01/14/2021",
      wo_id: "014",
      status: "Escalated L8",
    },
    {
      date: "01/15/2021",
      wo_id: "015",
      status: "Escalated L9",
    },
    {
      date: "01/16/2021",
      wo_id: "016",
      status: "Scheduled",
    },
    {
      date: "01/17/2021",
      wo_id: "017",
      status: "Not Assigned",
    },
    {
      date: "01/18/2021",
      wo_id: "018",
      status: "Escalated L10",
    },
    {
      date: "01/19/2021",
      wo_id: "019",
      status: "Escalated L11",
    },
  ],
  assets_equipments: [
    {
      date: "01/01/2021",
      equipment_id: "001",
      status: "Breakdown",
      healthy_hrs: 2800,
      warranty_date: "02/02/2021",
      total_downtime_hrs: 0,
    },
    {
      date: "01/02/2021",
      equipment_id: "002",
      status: "Operative",
      healthy_hrs: 2801,
      warranty_date: "02/03/2021",
      total_downtime_hrs: 1,
    },
    {
      date: "01/03/2021",
      equipment_id: "003",
      status: "Under Maintenance",
      healthy_hrs: 2802,
      warranty_date: "02/04/2021",
      total_downtime_hrs: 2,
    },
    {
      date: "01/04/2021",
      equipment_id: "004",
      status: "Breakdown",
      healthy_hrs: 2803,
      warranty_date: "02/05/2021",
      total_downtime_hrs: 3,
    },
    {
      date: "01/05/2021",
      equipment_id: "005",
      status: "Operative",
      healthy_hrs: 2804,
      warranty_date: "02/06/2021",
      total_downtime_hrs: 4,
    },
    {
      date: "01/06/2021",
      equipment_id: "006",
      status: "Under Maintenance",
      healthy_hrs: 2805,
      warranty_date: "02/07/2021",
      total_downtime_hrs: 5,
    },
    {
      date: "01/07/2021",
      equipment_id: "007",
      status: "Breakdown",
      healthy_hrs: 2806,
      warranty_date: "02/08/2021",
      total_downtime_hrs: 6,
    },
    {
      date: "01/08/2021",
      equipment_id: "008",
      status: "Operative",
      healthy_hrs: 2807,
      warranty_date: "02/09/2021",
      total_downtime_hrs: 7,
    },
    {
      date: "01/09/2021",
      equipment_id: "009",
      status: "Under Maintenance",
      healthy_hrs: 2808,
      warranty_date: "02/10/2021",
      total_downtime_hrs: 8,
    },
    {
      date: "01/10/2021",
      equipment_id: "010",
      status: "Breakdown",
      healthy_hrs: 2809,
      warranty_date: "02/11/2021",
      total_downtime_hrs: 9,
    },
    {
      date: "01/11/2021",
      equipment_id: "011",
      status: "Operative",
      healthy_hrs: 2810,
      warranty_date: "02/12/2021",
      total_downtime_hrs: 10,
    },
    {
      date: "01/12/2021",
      equipment_id: "012",
      status: "Under Maintenance",
      healthy_hrs: 2811,
      warranty_date: "02/13/2021",
      total_downtime_hrs: 11,
    },
    {
      date: "01/13/2021",
      equipment_id: "013",
      status: "Breakdown",
      healthy_hrs: 2812,
      warranty_date: "02/14/2021",
      total_downtime_hrs: 12,
    },
    {
      date: "01/14/2021",
      equipment_id: "014",
      status: "Operative",
      healthy_hrs: 2813,
      warranty_date: "02/15/2021",
      total_downtime_hrs: 13,
    },
    {
      date: "01/15/2021",
      equipment_id: "015",
      status: "Under Maintenance",
      healthy_hrs: 2814,
      warranty_date: "02/16/2021",
      total_downtime_hrs: 14,
    },
    {
      date: "01/16/2021",
      equipment_id: "016",
      status: "Breakdown",
      healthy_hrs: 2815,
      warranty_date: "02/17/2021",
      total_downtime_hrs: 15,
    },
    {
      date: "01/17/2021",
      equipment_id: "017",
      status: "Operative",
      healthy_hrs: 2816,
      warranty_date: "02/18/2021",
      total_downtime_hrs: 16,
    },
    {
      date: "01/18/2021",
      equipment_id: "018",
      status: "Under Maintenance",
      healthy_hrs: 2817,
      warranty_date: "02/19/2021",
      total_downtime_hrs: 17,
    },
    {
      date: "01/19/2021",
      equipment_id: "019",
      status: "Breakdown",
      healthy_hrs: 2818,
      warranty_date: "02/20/2021",
      total_downtime_hrs: 18,
    },
  ],
  tickets: [
    {
      date: "01/01/2021",
      ticket_id: "001",
      status: "New",
      sla: "Within SLA",
    },
    {
      date: "01/02/2021",
      ticket_id: "002",
      status: "Closed",
      sla: "Elapsed",
    },
    {
      date: "01/03/2021",
      ticket_id: "003",
      status: "In Progress",
      sla: "Within SLA",
    },
    {
      date: "01/04/2021",
      ticket_id: "004",
      status: "New",
      sla: "Elapsed",
    },
    {
      date: "01/05/2021",
      ticket_id: "005",
      status: "Closed",
      sla: "Elapsed",
    },
    {
      date: "01/06/2021",
      ticket_id: "006",
      status: "In Progress",
      sla: "Within SLA",
    },
    {
      date: "01/07/2021",
      ticket_id: "007",
      status: "New",
      sla: "Elapsed",
    },
    {
      date: "01/08/2021",
      ticket_id: "008",
      status: "Closed",
      sla: "Within SLA",
    },
    {
      date: "01/09/2021",
      ticket_id: "009",
      status: "In Progress",
      sla: "Within SLA",
    },
    {
      date: "01/10/2021",
      ticket_id: "010",
      status: "New",
      sla: "Within SLA",
    },
    {
      date: "01/11/2021",
      ticket_id: "011",
      status: "Closed",
      sla: "Within SLA",
    },
    {
      date: "01/12/2021",
      ticket_id: "012",
      status: "In Progress",
      sla: "Elapsed",
    },
    {
      date: "01/13/2021",
      ticket_id: "013",
      status: "New",
      sla: "Elapsed",
    },
    {
      date: "01/14/2021",
      ticket_id: "014",
      status: "Closed",
      sla: "Within SLA",
    },
    {
      date: "01/15/2021",
      ticket_id: "015",
      status: "In Progress",
      sla: "Within SLA",
    },
    {
      date: "01/16/2021",
      ticket_id: "016",
      status: "New",
      sla: "Elapsed",
    },
    {
      date: "01/17/2021",
      ticket_id: "017",
      status: "Closed",
      sla: "Within SLA",
    },
    {
      date: "01/18/2021",
      ticket_id: "018",
      status: "In Progress",
      sla: "Within SLA",
    },
    {
      date: "01/19/2021",
      ticket_id: "019",
      status: "New",
      sla: "Elapsed",
    },
  ],
  preventive_maintenances: [
    {
      date: "01/01/2021",
      equipment_id: "001",
      frequency: "Daily",
      status: "Done",
    },
    {
      date: "01/02/2021",
      equipment_id: "002",
      frequency: "Weekly",
      status: "Delayed",
    },
    {
      date: "01/03/2021",
      equipment_id: "003",
      frequency: "Monthly",
      status: "Done",
    },
    {
      date: "01/04/2021",
      equipment_id: "004",
      frequency: "Daily",
      status: "Done",
    },
    {
      date: "01/05/2021",
      equipment_id: "005",
      frequency: "Weekly",
      status: "Done",
    },
    {
      date: "01/06/2021",
      equipment_id: "006",
      frequency: "Monthly",
      status: "Delayed",
    },
    {
      date: "01/07/2021",
      equipment_id: "007",
      frequency: "Daily",
      status: "Done",
    },
    {
      date: "01/08/2021",
      equipment_id: "008",
      frequency: "Weekly",
      status: "Done",
    },
    {
      date: "01/09/2021",
      equipment_id: "009",
      frequency: "Monthly",
      status: "Done",
    },
    {
      date: "01/10/2021",
      equipment_id: "010",
      frequency: "Daily",
      status: "Delayed",
    },
    {
      date: "01/11/2021",
      equipment_id: "011",
      frequency: "Weekly",
      status: "Done",
    },
    {
      date: "01/12/2021",
      equipment_id: "012",
      frequency: "Monthly",
      status: "Done",
    },
    {
      date: "01/13/2021",
      equipment_id: "013",
      frequency: "Daily",
      status: "Done",
    },
    {
      date: "01/14/2021",
      equipment_id: "014",
      frequency: "Weekly",
      status: "Delayed",
    },
    {
      date: "01/15/2021",
      equipment_id: "015",
      frequency: "Monthly",
      status: "Done",
    },
    {
      date: "01/16/2021",
      equipment_id: "016",
      frequency: "Daily",
      status: "Done",
    },
    {
      date: "01/17/2021",
      equipment_id: "017",
      frequency: "Weekly",
      status: "Done",
    },
    {
      date: "01/18/2021",
      equipment_id: "018",
      frequency: "Monthly",
      status: "Delayed",
    },
    {
      date: "01/19/2021",
      equipment_id: "019",
      frequency: "Daily",
      status: "Done",
    },
  ],
  visitors: [
    {
      date: "01/01/2021",
      visitor_id: "001",
      status: "Scheduled",
    },
    {
      date: "01/02/2021",
      visitor_id: "002",
      status: "Currently Inside",
    },
    {
      date: "01/03/2021",
      visitor_id: "003",
      status: "Cancelled",
    },
    {
      date: "01/04/2021",
      visitor_id: "004",
      status: "Scheduled",
    },
    {
      date: "01/05/2021",
      visitor_id: "005",
      status: "Currently Inside",
    },
    {
      date: "01/06/2021",
      visitor_id: "006",
      status: "Cancelled",
    },
    {
      date: "01/07/2021",
      visitor_id: "007",
      status: "Scheduled",
    },
    {
      date: "01/08/2021",
      visitor_id: "008",
      status: "Currently Inside",
    },
    {
      date: "01/09/2021",
      visitor_id: "009",
      status: "Cancelled",
    },
    {
      date: "01/10/2021",
      visitor_id: "010",
      status: "Scheduled",
    },
    {
      date: "01/11/2021",
      visitor_id: "011",
      status: "Currently Inside",
    },
    {
      date: "01/12/2021",
      visitor_id: "012",
      status: "Cancelled",
    },
    {
      date: "01/13/2021",
      visitor_id: "013",
      status: "Scheduled",
    },
    {
      date: "01/14/2021",
      visitor_id: "014",
      status: "Currently Inside",
    },
    {
      date: "01/15/2021",
      visitor_id: "015",
      status: "Cancelled",
    },
    {
      date: "01/16/2021",
      visitor_id: "016",
      status: "Scheduled",
    },
    {
      date: "01/17/2021",
      visitor_id: "017",
      status: "Currently Inside",
    },
    {
      date: "01/18/2021",
      visitor_id: "018",
      status: "Cancelled",
    },
    {
      date: "01/19/2021",
      visitor_id: "019",
      status: "Scheduled",
    },
  ],
  inventory: [
    {
      id: 1,
      date: "01/01/2021",
      site: "MSFT - A",
      warehouse: "Warehouse 1",
      product: "Cable Tie",
      status: "Below Threshold",
      action: 0,
    },
    {
      id: 2,
      date: "01/02/2021",
      site: "MSFT - B",
      warehouse: "Warehouse 2",
      product: "Air Filter",
      status: "Fast Moving",
      action: 0,
    },
    {
      id: 3,
      date: "01/03/2021",
      site: "MSFT - C",
      warehouse: "Warehouse 3",
      product: "Tape",
      status: "Not Available",
      action: 0,
    },
    {
      id: 4,
      date: "01/04/2021",
      site: "MSFT - D",
      warehouse: "Warehouse 4",
      product: "Cable Tie",
      status: "Below Threshold",
      action: 0,
    },
    {
      id: 5,
      date: "01/05/2021",
      site: "MSFT - A",
      warehouse: "Warehouse 5",
      product: "Air Filter",
      status: "Fast Moving",
      action: 0,
    },
    {
      id: 6,
      date: "01/06/2021",
      site: "MSFT - B",
      warehouse: "Warehouse 6",
      product: "Tape",
      status: "Not Available",
      action: 0,
    },
    {
      id: 7,
      date: "01/07/2021",
      site: "MSFT - C",
      warehouse: "Warehouse 7",
      product: "Cable Tie",
      status: "Below Threshold",
      action: 0,
    },
    {
      id: 8,
      date: "01/08/2021",
      site: "MSFT - D",
      warehouse: "Warehouse 8",
      product: "Air Filter",
      status: "Fast Moving",
      action: 0,
    },
    {
      id: 9,
      date: "01/09/2021",
      site: "MSFT - A",
      warehouse: "Warehouse 9",
      product: "Tape",
      status: "Not Available",
      action: 0,
    },
    {
      id: 10,
      date: "01/10/2021",
      site: "MSFT - B",
      warehouse: "Warehouse 10",
      product: "Cable Tie",
      status: "Below Threshold",
      action: 0,
    },
    {
      id: 11,
      date: "01/11/2021",
      site: "MSFT - C",
      warehouse: "Warehouse 11",
      product: "Air Filter",
      status: "Fast Moving",
      action: 0,
    },
    {
      id: 12,
      date: "01/12/2021",
      site: "MSFT - D",
      warehouse: "Warehouse 12",
      product: "Tape",
      status: "Not Available",
      action: 0,
    },
    {
      id: 13,
      date: "01/13/2021",
      site: "MSFT - A",
      warehouse: "Warehouse 13",
      product: "Cable Tie",
      status: "Below Threshold",
      action: 0,
    },
    {
      id: 14,
      date: "01/14/2021",
      site: "MSFT - B",
      warehouse: "Warehouse 14",
      product: "Air Filter",
      status: "Fast Moving",
      action: 0,
    },
    {
      id: 15,
      date: "01/15/2021",
      site: "MSFT - C",
      warehouse: "Warehouse 15",
      product: "Tape",
      status: "Not Available",
      action: 0,
    },
    {
      id: 16,
      date: "01/16/2021",
      site: "MSFT - D",
      warehouse: "Warehouse 16",
      product: "Cable Tie",
      status: "Below Threshold",
      action: 0,
    },
    {
      id: 17,
      date: "01/17/2021",
      site: "MSFT - A",
      warehouse: "Warehouse 17",
      product: "Air Filter",
      status: "Fast Moving",
      action: 0,
    },
    {
      id: 18,
      date: "01/18/2021",
      site: "MSFT - B",
      warehouse: "Warehouse 18",
      product: "Tape",
      status: "Not Available",
      action: 0,
    },
    {
      id: 19,
      date: "01/19/2021",
      site: "MSFT - C",
      warehouse: "Warehouse 19",
      product: "Cable Tie",
      status: "Below Threshold",
      action: 0,
    },
  ],
  building_compliances: [
    {
      id: 1,
      building: "MCloud",
      floor: "1st Floor",
      certificate_type: "Fire",
      certificate_expiry_date: "08/15/2021",
      certificate_status: "About to Expire",
      action: "ARN/02/52",
    },
    {
      id: 2,
      building: "Miscrosoft",
      floor: "2nd Floor",
      certificate_type: "EHS",
      certificate_expiry_date: "07/27/2021",
      certificate_status: "In Process of Renewal",
    },
    {
      id: 3,
      building: "CTS",
      floor: "Ground Floor",
      certificate_type: "Fire",
      certificate_expiry_date: "07/15/2021",
      certificate_status: "Expired",
      action: "ARN/02/53",
    },
    {
      id: 4,
      building: "MCloud",
      floor: "1st Floor",
      certificate_type: "EHS",
      certificate_expiry_date: "08/15/2021",
      certificate_status: "About to Expire",
    },
    {
      id: 5,
      building: "Miscrosoft",
      floor: "2nd Floor",
      certificate_type: "Fire",
      certificate_expiry_date: "07/27/2021",
      certificate_status: "In Process of Renewal",
      action: "ARN/02/54",
    },
    {
      id: 6,
      building: "CTS",
      floor: "Ground Floor",
      certificate_type: "EHS",
      certificate_expiry_date: "07/15/2021",
      certificate_status: "Expired",
    },
    {
      id: 7,
      building: "MCloud",
      floor: "1st Floor",
      certificate_type: "Fire",
      certificate_expiry_date: "08/15/2021",
      certificate_status: "About to Expire",
      action: "ARN/02/55",
    },
    {
      id: 8,
      building: "Miscrosoft",
      floor: "2nd Floor",
      certificate_type: "EHS",
      certificate_expiry_date: "07/27/2021",
      certificate_status: "In Process of Renewal",
    },
    {
      id: 9,
      building: "CTS",
      floor: "Ground Floor",
      certificate_type: "Fire",
      certificate_expiry_date: "07/15/2021",
      certificate_status: "Expired",
      action: "ARN/02/56",
    },
    {
      id: 10,
      building: "MCloud",
      floor: "1st Floor",
      certificate_type: "EHS",
      certificate_expiry_date: "08/15/2021",
      certificate_status: "About to Expire",
    },
    {
      id: 11,
      building: "Miscrosoft",
      floor: "2nd Floor",
      certificate_type: "Fire",
      certificate_expiry_date: "07/27/2021",
      certificate_status: "In Process of Renewal",
      action: "ARN/02/57",
    },
    {
      id: 12,
      building: "CTS",
      floor: "Ground Floor",
      certificate_type: "EHS",
      certificate_expiry_date: "07/15/2021",
      certificate_status: "Expired",
    },
    {
      id: 13,
      building: "MCloud",
      floor: "1st Floor",
      certificate_type: "Fire",
      certificate_expiry_date: "08/15/2021",
      certificate_status: "About to Expire",
      action: "ARN/02/58",
    },
    {
      id: 14,
      building: "Miscrosoft",
      floor: "2nd Floor",
      certificate_type: "EHS",
      certificate_expiry_date: "07/27/2021",
      certificate_status: "In Process of Renewal",
    },
    {
      id: 15,
      building: "CTS",
      floor: "Ground Floor",
      certificate_type: "Fire",
      certificate_expiry_date: "07/15/2021",
      certificate_status: "Expired",
      action: "ARN/02/59",
    },
    {
      id: 16,
      building: "MCloud",
      floor: "1st Floor",
      certificate_type: "EHS",
      certificate_expiry_date: "08/15/2021",
      certificate_status: "About to Expire",
    },
    {
      id: 17,
      building: "Miscrosoft",
      floor: "2nd Floor",
      certificate_type: "Fire",
      certificate_expiry_date: "07/27/2021",
      certificate_status: "In Process of Renewal",
      action: "ARN/02/60",
    },
    {
      id: 18,
      building: "CTS",
      floor: "Ground Floor",
      certificate_type: "EHS",
      certificate_expiry_date: "07/15/2021",
      certificate_status: "Expired",
    },
    {
      id: 19,
      building: "MCloud",
      floor: "1st Floor",
      certificate_type: "Fire",
      certificate_expiry_date: "08/15/2021",
      certificate_status: "About to Expire",
      action: "ARN/02/61",
    },
  ],
};

export default data;
