const data = {
  assets_details: [
    {
      id: 1,
      equipment_name: "Equipment 1",
      equipment_number: "DTP-E-001",
      category: "Electrical/Generator",
      space: "DTPT/BC11/F1",
      status: "Operative",
      warranty_end: "01/10/2021",
      company: "Technopark",
    },
    {
      id: 2,
      equipment_name: "Equipment 2",
      equipment_number: "DTP-E-002",
      category: "HVAC",
      space: "DTPT/BC11/F2",
      status: "Operative",
      warranty_end: "02/20/2022",
      company: "Technopark",
    },
    {
      id: 3,
      equipment_name: "Equipment 3",
      equipment_number: "DTP-E-003",
      category: "Electrical/Generator",
      space: "DTPT/BC11/F3",
      status: "Operative",
      warranty_end: "02/21/2022",
      company: "Technopark",
    },
    {
      id: 4,
      equipment_name: "Equipment 4",
      equipment_number: "DTP-E-004",
      category: "HVAC",
      space: "DTPT/BC11/F4",
      status: "Operative",
      warranty_end: "02/22/2022",
      company: "Technopark",
    },
    {
      id: 5,
      equipment_name: "Equipment 5",
      equipment_number: "DTP-E-005",
      category: "Electrical/Generator",
      space: "DTPT/BC11/F5",
      status: "Operative",
      warranty_end: "02/23/2022",
      company: "Technopark",
    },
    {
      id: 6,
      equipment_name: "Equipment 6",
      equipment_number: "DTP-E-006",
      category: "HVAC",
      space: "DTPT/BC11/F6",
      status: "Operative",
      warranty_end: "02/24/2022",
      company: "Technopark",
    },
    {
      id: 7,
      equipment_name: "Equipment 7",
      equipment_number: "DTP-E-007",
      category: "Electrical/Generator",
      space: "DTPT/BC11/F7",
      status: "Operative",
      warranty_end: "02/25/2022",
      company: "Technopark",
    },
    {
      id: 8,
      equipment_name: "Equipment 8",
      equipment_number: "DTP-E-008",
      category: "HVAC",
      space: "DTPT/BC11/F8",
      status: "Under Maintenance",
      warranty_end: "02/26/2022",
      company: "Technopark",
    },
    {
      id: 9,
      equipment_name: "Equipment 9",
      equipment_number: "DTP-E-009",
      category: "Electrical/Generator",
      space: "DTPT/BC11/F9",
      status: "Under Maintenance",
      warranty_end: "02/27/2022",
      company: "Technopark",
    },
    {
      id: 10,
      equipment_name: "Equipment 10",
      equipment_number: "DTP-E-010",
      category: "HVAC",
      space: "DTPT/BC11/F10",
      status: "Under Maintenance",
      warranty_end: "02/28/2022",
      company: "Technopark",
    },
    {
      id: 11,
      equipment_name: "Equipment 11",
      equipment_number: "DTP-E-011",
      category: "Electrical/Generator",
      space: "DTPT/BC11/F11",
      status: "Under Maintenance",
      warranty_end: "03/01/2022",
      company: "Technopark",
    },
    {
      id: 12,
      equipment_name: "Equipment 12",
      equipment_number: "DTP-E-012",
      category: "HVAC",
      space: "DTPT/BC11/F12",
      status: "Under Maintenance",
      warranty_end: "03/02/2022",
      company: "Chino",
    },
    {
      id: 13,
      equipment_name: "Equipment 13",
      equipment_number: "DTP-E-013",
      category: "Electrical/Generator",
      space: "DTPT/BC11/F13",
      status: "Under Maintenance",
      warranty_end: "03/03/2022",
      company: "Chino",
    },
    {
      id: 14,
      equipment_name: "Equipment 14",
      equipment_number: "DTP-E-014",
      category: "HVAC",
      space: "DTPT/BC11/F14",
      status: "Breakdown",
      warranty_end: "03/04/2022",
      company: "Chino",
    },
    {
      id: 15,
      equipment_name: "Equipment 15",
      equipment_number: "DTP-E-015",
      category: "Electrical/Generator",
      space: "DTPT/BC11/F15",
      status: "Breakdown",
      warranty_end: "03/05/2022",
      company: "Chino",
    },
    {
      id: 16,
      equipment_name: "Equipment 16",
      equipment_number: "DTP-E-016",
      category: "HVAC",
      space: "DTPT/BC11/F16",
      status: "Breakdown",
      warranty_end: "03/06/2022",
      company: "Chino",
    },
    {
      id: 17,
      equipment_name: "Equipment 17",
      equipment_number: "DTP-E-017",
      category: "Electrical/Generator",
      space: "DTPT/BC11/F17",
      status: "Breakdown",
      warranty_end: "03/07/2022",
      company: "Chino",
    },
    {
      id: 18,
      equipment_name: "Equipment 18",
      equipment_number: "DTP-E-018",
      category: "HVAC",
      space: "DTPT/BC11/F18",
      status: "Breakdown",
      warranty_end: "03/08/2022",
      company: "Chino",
    },
    {
      id: 19,
      equipment_name: "Equipment 19",
      equipment_number: "DTP-E-019",
      category: "Electrical/Generator",
      space: "DTPT/BC11/F19",
      status: "Breakdown",
      warranty_end: "03/09/2022",
      company: "Chino",
    },
  ],
  work_orders: [
    {
      id: 1,
      equipment_name: "Equipment 1",
      equipment_number: "DTP-E-001",
      maintenance_type: "Corrective",
      priority: "Normal",
      maintenance_team: "C1-Electrician Team",
      technician: "Arun Kumar",
      status: "Ready to Maintenance",
      company: "Technopark",
    },
    {
      id: 2,
      equipment_name: "Equipment 2",
      equipment_number: "DTP-E-002",
      maintenance_type: "Preventive",
      priority: "High",
      maintenance_team: "A1-Fire Team",
      technician: "John Davis",
      status: "Ready to Maintenance",
      company: "Technopark",
    },
    {
      id: 3,
      equipment_name: "Equipment 3",
      equipment_number: "DTP-E-003",
      maintenance_type: "On Condition",
      priority: "Low",
      maintenance_team: "C1-DG Operator Team",
      technician: "Arun Kumar",
      status: "Ready to Maintenance",
      company: "Technopark",
    },
    {
      id: 4,
      equipment_name: "Equipment 4",
      equipment_number: "DTP-E-004",
      maintenance_type: "Periodic",
      priority: "Normal",
      maintenance_team: "C1-Electrician Team",
      technician: "John Davis",
      status: "Ready to Maintenance",
      company: "Technopark",
    },
    {
      id: 5,
      equipment_name: "Equipment 5",
      equipment_number: "DTP-E-005",
      maintenance_type: "Corrective",
      priority: "High",
      maintenance_team: "A1-Fire Team",
      technician: "Arun Kumar",
      status: "Ready to Maintenance",
      company: "Technopark",
    },
    {
      id: 6,
      equipment_name: "Equipment 6",
      equipment_number: "DTP-E-006",
      maintenance_type: "Preventive",
      priority: "Low",
      maintenance_team: "C1-DG Operator Team",
      technician: "John Davis",
      status: "Ready to Maintenance",
      company: "Technopark",
    },
    {
      id: 7,
      equipment_name: "Equipment 7",
      equipment_number: "DTP-E-007",
      maintenance_type: "On Condition",
      priority: "Normal",
      maintenance_team: "C1-Electrician Team",
      technician: "Arun Kumar",
      status: "Ready to Maintenance",
      company: "Technopark",
    },
    {
      id: 8,
      equipment_name: "Equipment 8",
      equipment_number: "DTP-E-008",
      maintenance_type: "Periodic",
      priority: "High",
      maintenance_team: "A1-Fire Team",
      technician: "John Davis",
      status: "Ready to Maintenance",
      company: "Technopark",
    },
    {
      id: 9,
      equipment_name: "Equipment 9",
      equipment_number: "DTP-E-009",
      maintenance_type: "Corrective",
      priority: "Low",
      maintenance_team: "C1-DG Operator Team",
      technician: "Arun Kumar",
      status: "Ready to Maintenance",
      company: "Technopark",
    },
    {
      id: 10,
      equipment_name: "Equipment 10",
      equipment_number: "DTP-E-010",
      maintenance_type: "Preventive",
      priority: "Normal",
      maintenance_team: "C1-Electrician Team",
      technician: "John Davis",
      status: "Ready to Maintenance",
      company: "Technopark",
    },
    {
      id: 11,
      equipment_name: "Equipment 11",
      equipment_number: "DTP-E-011",
      maintenance_type: "On Condition",
      priority: "High",
      maintenance_team: "A1-Fire Team",
      technician: "Arun Kumar",
      status: "Ready to Maintenance",
      company: "Technopark",
    },
    {
      id: 12,
      equipment_name: "Equipment 12",
      equipment_number: "DTP-E-012",
      maintenance_type: "Periodic",
      priority: "Low",
      maintenance_team: "C1-DG Operator Team",
      technician: "John Davis",
      status: "Ready to Maintenance",
      company: "Chino",
    },
    {
      id: 13,
      equipment_name: "Equipment 13",
      equipment_number: "DTP-E-013",
      maintenance_type: "Corrective",
      priority: "Normal",
      maintenance_team: "C1-Electrician Team",
      technician: "Arun Kumar",
      status: "Ready to Maintenance",
      company: "Chino",
    },
    {
      id: 14,
      equipment_name: "Equipment 14",
      equipment_number: "DTP-E-014",
      maintenance_type: "Preventive",
      priority: "High",
      maintenance_team: "A1-Fire Team",
      technician: "John Davis",
      status: "Ready to Maintenance",
      company: "Chino",
    },
    {
      id: 15,
      equipment_name: "Equipment 15",
      equipment_number: "DTP-E-015",
      maintenance_type: "On Condition",
      priority: "Low",
      maintenance_team: "C1-DG Operator Team",
      technician: "Arun Kumar",
      status: "Ready to Maintenance",
      company: "Chino",
    },
    {
      id: 16,
      equipment_name: "Equipment 16",
      equipment_number: "DTP-E-016",
      maintenance_type: "Periodic",
      priority: "Normal",
      maintenance_team: "C1-Electrician Team",
      technician: "John Davis",
      status: "Ready to Maintenance",
      company: "Chino",
    },
    {
      id: 17,
      equipment_name: "Equipment 17",
      equipment_number: "DTP-E-017",
      maintenance_type: "Corrective",
      priority: "High",
      maintenance_team: "A1-Fire Team",
      technician: "Arun Kumar",
      status: "Ready to Maintenance",
      company: "Chino",
    },
    {
      id: 18,
      equipment_name: "Equipment 18",
      equipment_number: "DTP-E-018",
      maintenance_type: "Preventive",
      priority: "Low",
      maintenance_team: "C1-DG Operator Team",
      technician: "John Davis",
      status: "Ready to Maintenance",
      company: "Chino",
    },
    {
      id: 19,
      equipment_name: "Equipment 19",
      equipment_number: "DTP-E-019",
      maintenance_type: "On Condition",
      priority: "Normal",
      maintenance_team: "C1-Electrician Team",
      technician: "Arun Kumar",
      status: "Ready to Maintenance",
      company: "Chino",
    },
  ],
  TP_engineering_dashboard: [
    {
      id: 1,
      sequence_number: "DTPT-21-1000",
      tanker_transaction: "Himalaya Water - Supply Water",
      vendor: "Himalaya",
      block: "DTPT/BC11",
      in_date: "04/04/2021 05:00 AM",
      commodity: "Water",
      capacity: "18726",
      company: "Technopark",
    },
    {
      id: 2,
      sequence_number: "DTPT-21-1001",
      tanker_transaction: "Kavya Petro - Park Water",
      vendor: "Kavya",
      block: "DTPT/BC12",
      in_date: "04/05/2021 05:00 AM",
      commodity: "Oil",
      capacity: "18342",
      company: "Technopark",
    },
    {
      id: 3,
      sequence_number: "DTPT-21-1002",
      tanker_transaction: "S V Enterprises - Water",
      vendor: "S V",
      block: "DTPT/BC13",
      in_date: "04/06/2021 05:00 AM",
      commodity: "Water",
      capacity: "23786",
      company: "Technopark",
    },
    {
      id: 4,
      sequence_number: "DTPT-21-1003",
      tanker_transaction: "Himalaya Water - Supply Water",
      vendor: "Himalaya",
      block: "DTPT/BC14",
      in_date: "04/07/2021 05:00 AM",
      commodity: "Water",
      capacity: "19150",
      company: "Technopark",
    },
    {
      id: 5,
      sequence_number: "DTPT-21-1004",
      tanker_transaction: "Kavya Petro - Park Water",
      vendor: "Kavya",
      block: "DTPT/BC15",
      in_date: "04/08/2021 05:00 AM",
      commodity: "Oil",
      capacity: "19358",
      company: "Technopark",
    },
    {
      id: 6,
      sequence_number: "DTPT-21-1005",
      tanker_transaction: "S V Enterprises - Water",
      vendor: "S V",
      block: "DTPT/BC16",
      in_date: "04/09/2021 05:00 AM",
      commodity: "Water",
      capacity: "23078",
      company: "Technopark",
    },
    {
      id: 7,
      sequence_number: "DTPT-21-1006",
      tanker_transaction: "Himalaya Water - Supply Water",
      vendor: "Himalaya",
      block: "DTPT/BC17",
      in_date: "04/10/2021 05:00 AM",
      commodity: "Water",
      capacity: "22526",
      company: "Technopark",
    },
    {
      id: 8,
      sequence_number: "DTPT-21-1007",
      tanker_transaction: "Kavya Petro - Park Water",
      vendor: "Kavya",
      block: "DTPT/BC18",
      in_date: "04/11/2021 05:00 AM",
      commodity: "Oil",
      capacity: "21180",
      company: "Technopark",
    },
    {
      id: 9,
      sequence_number: "DTPT-21-1008",
      tanker_transaction: "S V Enterprises - Water",
      vendor: "S V",
      block: "DTPT/BC19",
      in_date: "04/12/2021 05:00 AM",
      commodity: "Water",
      capacity: "20813",
      company: "Technopark",
    },
    {
      id: 10,
      sequence_number: "DTPT-21-1009",
      tanker_transaction: "Himalaya Water - Supply Water",
      vendor: "Himalaya",
      block: "DTPT/BC20",
      in_date: "04/13/2021 05:00 AM",
      commodity: "Water",
      capacity: "22027",
      company: "Technopark",
    },
    {
      id: 11,
      sequence_number: "DTPT-21-1010",
      tanker_transaction: "Kavya Petro - Park Water",
      vendor: "Kavya",
      block: "DTPT/BC21",
      in_date: "04/14/2021 05:00 AM",
      commodity: "Oil",
      capacity: "18042",
      company: "Technopark",
    },
    {
      id: 12,
      sequence_number: "DTPT-21-1011",
      tanker_transaction: "S V Enterprises - Water",
      vendor: "S V",
      block: "DTPT/BC22",
      in_date: "04/15/2021 05:00 AM",
      commodity: "Water",
      capacity: "15466",
      company: "Technopark",
    },
    {
      id: 13,
      sequence_number: "DTPT-21-1012",
      tanker_transaction: "Himalaya Water - Supply Water",
      vendor: "Himalaya",
      block: "DTPT/BC23",
      in_date: "04/16/2021 05:00 AM",
      commodity: "Water",
      capacity: "16335",
      company: "Technopark",
    },
    {
      id: 14,
      sequence_number: "DTPT-21-1013",
      tanker_transaction: "Kavya Petro - Park Water",
      vendor: "Kavya",
      block: "DTPT/BC24",
      in_date: "04/17/2021 05:00 AM",
      commodity: "Oil",
      capacity: "16751",
      company: "Chino",
    },
    {
      id: 15,
      sequence_number: "DTPT-21-1014",
      tanker_transaction: "S V Enterprises - Water",
      vendor: "S V",
      block: "DTPT/BC25",
      in_date: "04/18/2021 05:00 AM",
      commodity: "Water",
      capacity: "19151",
      company: "Chino",
    },
    {
      id: 16,
      sequence_number: "DTPT-21-1015",
      tanker_transaction: "Himalaya Water - Supply Water",
      vendor: "Himalaya",
      block: "DTPT/BC26",
      in_date: "04/19/2021 05:00 AM",
      commodity: "Water",
      capacity: "21316",
      company: "Chino",
    },
    {
      id: 17,
      sequence_number: "DTPT-21-1016",
      tanker_transaction: "Kavya Petro - Park Water",
      vendor: "Kavya",
      block: "DTPT/BC27",
      in_date: "04/20/2021 05:00 AM",
      commodity: "Oil",
      capacity: "24287",
      company: "Chino",
    },
    {
      id: 18,
      sequence_number: "DTPT-21-1017",
      tanker_transaction: "S V Enterprises - Water",
      vendor: "S V",
      block: "DTPT/BC28",
      in_date: "04/21/2021 05:00 AM",
      commodity: "Water",
      capacity: "22359",
      company: "Chino",
    },
    {
      id: 19,
      sequence_number: "DTPT-21-1018",
      tanker_transaction: "Himalaya Water - Supply Water",
      vendor: "Himalaya",
      block: "DTPT/BC29",
      in_date: "04/22/2021 05:00 AM",
      commodity: "Water",
      capacity: "22492",
      company: "Chino",
    },
  ],
};

export default data;
