const data = {
  covid: [
    {
      date: "01/01/2021",
      case_id: "0001",
      status: "Recovered",
    },
    {
      date: "01/02/2021",
      case_id: "0002",
      status: "Active",
    },
    {
      date: "01/03/2021",
      case_id: "0003",
      status: "New",
    },
    {
      date: "01/04/2021",
      case_id: "0004",
      status: "Recovered",
    },
    {
      date: "01/05/2021",
      case_id: "0005",
      status: "Active",
    },
    {
      date: "01/06/2021",
      case_id: "0006",
      status: "New",
    },
    {
      date: "01/07/2021",
      case_id: "0007",
      status: "Recovered",
    },
    {
      date: "01/08/2021",
      case_id: "0008",
      status: "Active",
    },
    {
      date: "01/09/2021",
      case_id: "0009",
      status: "New",
    },
    {
      date: "01/10/2021",
      case_id: "0010",
      status: "Recovered",
    },
    {
      date: "01/11/2021",
      case_id: "0011",
      status: "Active",
    },
    {
      date: "01/12/2021",
      case_id: "0012",
      status: "New",
    },
    {
      date: "01/13/2021",
      case_id: "0013",
      status: "Recovered",
    },
    {
      date: "01/14/2021",
      case_id: "0014",
      status: "Active",
    },
    {
      date: "01/15/2021",
      case_id: "0015",
      status: "New",
    },
    {
      date: "01/16/2021",
      case_id: "0016",
      status: "Recovered",
    },
    {
      date: "01/17/2021",
      case_id: "0017",
      status: "Active",
    },
    {
      date: "01/18/2021",
      case_id: "0018",
      status: "New",
    },
    {
      date: "01/19/2021",
      case_id: "0019",
      status: "Recovered",
    },
  ],
  meeting_room_occupancy: [
    {
      date: "01/01/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 12,
      total_seats: 100,
    },
    {
      date: "01/02/2021",
      meeting_room: "Meeting Room 1",
      status: "Free",
      seats_vacant: 19,
      total_seats: 100,
    },
    {
      date: "01/03/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 6,
      total_seats: 100,
    },
    {
      date: "01/04/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 4,
      total_seats: 100,
    },
    {
      date: "01/05/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 5,
      total_seats: 100,
    },
    {
      date: "01/06/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 6,
      total_seats: 100,
    },
    {
      date: "01/07/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 4,
      total_seats: 100,
    },
    {
      date: "01/08/2021",
      meeting_room: "Meeting Room 1",
      status: "Free",
      seats_vacant: 4,
      total_seats: 100,
    },
    {
      date: "01/09/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 4,
      total_seats: 100,
    },
    {
      date: "01/10/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 4,
      total_seats: 100,
    },
    {
      date: "01/11/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 4,
      total_seats: 100,
    },
    {
      date: "01/12/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 4,
      total_seats: 100,
    },
    {
      date: "01/13/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 4,
      total_seats: 100,
    },
    {
      date: "01/14/2021",
      meeting_room: "Meeting Room 1",
      status: "Free",
      seats_vacant: 4,
      total_seats: 100,
    },
    {
      date: "01/15/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 4,
      total_seats: 100,
    },
    {
      date: "01/16/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 4,
      total_seats: 100,
    },
    {
      date: "01/17/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 4,
      total_seats: 100,
    },
    {
      date: "01/18/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 4,
      total_seats: 100,
    },
    {
      date: "01/19/2021",
      meeting_room: "Meeting Room 1",
      status: "Occupied",
      seats_vacant: 4,
      total_seats: 100,
    },
  ],
  attendance_management: [
    {
      id: 1,
      date: "01/01/2021",
      site: "MSFT - A",
      team: "Housekeeping",
      scheduled_hrs_per_day: 48,
      performed_hrs_per_day: 40,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
    {
      id: 2,
      date: "01/02/2021",
      site: "MSFT - B",
      team: "IT",
      scheduled_hrs_per_day: 480,
      performed_hrs_per_day: 720,
      deviation: 1.5,
      action: "Get Approval from Manager",
    },
    {
      id: 3,
      date: "01/03/2021",
      site: "MSFT - C",
      team: "Electrical",
      scheduled_hrs_per_day: 480,
      performed_hrs_per_day: 360,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
    {
      id: 4,
      date: "01/04/2021",
      site: "MSFT - D",
      team: "Sales",
      scheduled_hrs_per_day: 48,
      performed_hrs_per_day: 40,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
    {
      id: 5,
      date: "01/05/2021",
      site: "MSFT - A",
      team: "Housekeeping",
      scheduled_hrs_per_day: 48,
      performed_hrs_per_day: 40,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
    {
      id: 6,
      date: "01/06/2021",
      site: "MSFT - B",
      team: "IT",
      scheduled_hrs_per_day: 480,
      performed_hrs_per_day: 720,
      deviation: 1.5,
      action: "Get Approval from Manager",
    },
    {
      id: 7,
      date: "01/07/2021",
      site: "MSFT - C",
      team: "Electrical",
      scheduled_hrs_per_day: 480,
      performed_hrs_per_day: 360,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
    {
      id: 8,
      date: "01/08/2021",
      site: "MSFT - D",
      team: "Sales",
      scheduled_hrs_per_day: 48,
      performed_hrs_per_day: 40,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
    {
      id: 9,
      date: "01/09/2021",
      site: "MSFT - A",
      team: "Housekeeping",
      scheduled_hrs_per_day: 48,
      performed_hrs_per_day: 40,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
    {
      id: 10,
      date: "01/10/2021",
      site: "MSFT - B",
      team: "IT",
      scheduled_hrs_per_day: 480,
      performed_hrs_per_day: 720,
      deviation: 1.5,
      action: "Get Approval from Manager",
    },
    {
      id: 11,
      date: "01/11/2021",
      site: "MSFT - C",
      team: "Electrical",
      scheduled_hrs_per_day: 480,
      performed_hrs_per_day: 360,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
    {
      id: 12,
      date: "01/12/2021",
      site: "MSFT - D",
      team: "Sales",
      scheduled_hrs_per_day: 48,
      performed_hrs_per_day: 40,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
    {
      id: 13,
      date: "01/13/2021",
      site: "MSFT - A",
      team: "Housekeeping",
      scheduled_hrs_per_day: 48,
      performed_hrs_per_day: 40,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
    {
      id: 14,
      date: "01/14/2021",
      site: "MSFT - B",
      team: "IT",
      scheduled_hrs_per_day: 480,
      performed_hrs_per_day: 720,
      deviation: 1.5,
      action: "Get Approval from Manager",
    },
    {
      id: 15,
      date: "01/15/2021",
      site: "MSFT - C",
      team: "Electrical",
      scheduled_hrs_per_day: 480,
      performed_hrs_per_day: 360,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
    {
      id: 16,
      date: "01/16/2021",
      site: "MSFT - D",
      team: "Sales",
      scheduled_hrs_per_day: 48,
      performed_hrs_per_day: 40,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
    {
      id: 17,
      date: "01/17/2021",
      site: "MSFT - A",
      team: "Housekeeping",
      scheduled_hrs_per_day: 48,
      performed_hrs_per_day: 40,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
    {
      id: 18,
      date: "01/18/2021",
      site: "MSFT - B",
      team: "IT",
      scheduled_hrs_per_day: 480,
      performed_hrs_per_day: 720,
      deviation: 1.5,
      action: "Get Approval from Manager",
    },
    {
      id: 19,
      date: "01/19/2021",
      site: "MSFT - C",
      team: "Electrical",
      scheduled_hrs_per_day: 480,
      performed_hrs_per_day: 360,
      deviation: 0.8,
      action: "Staff Absent/Shift",
    },
  ],
  critical_alerts: [
    {
      date: "01/01/2021",
      reported_issue: "No of people have not taken test today",
    },
    {
      date: "01/02/2021",
      reported_issue: "No of people have answered they have cough today",
    },
    {
      date: "01/03/2021",
      reported_issue:
        "No of people have answered they have cough but not fever",
    },
    {
      date: "01/04/2021",
      reported_issue: "No of people have not taken test today",
    },
    {
      date: "01/05/2021",
      reported_issue: "No of people have answered they have cough today",
    },
    {
      date: "01/06/2021",
      reported_issue:
        "No of people have answered they have cough but not fever",
    },
    {
      date: "01/07/2021",
      reported_issue: "No of people have not taken test today",
    },
    {
      date: "01/08/2021",
      reported_issue: "No of people have answered they have cough today",
    },
    {
      date: "01/09/2021",
      reported_issue:
        "No of people have answered they have cough but not fever",
    },
    {
      date: "01/10/2021",
      reported_issue: "No of people have not taken test today",
    },
    {
      date: "01/11/2021",
      reported_issue: "No of people have answered they have cough today",
    },
    {
      date: "01/12/2021",
      reported_issue:
        "No of people have answered they have cough but not fever",
    },
    {
      date: "01/13/2021",
      reported_issue: "No of people have not taken test today",
    },
    {
      date: "01/14/2021",
      reported_issue: "No of people have answered they have cough today",
    },
    {
      date: "01/15/2021",
      reported_issue:
        "No of people have answered they have cough but not fever",
    },
    {
      date: "01/16/2021",
      reported_issue: "No of people have not taken test today",
    },
    {
      date: "01/17/2021",
      reported_issue: "No of people have answered they have cough today",
    },
    {
      date: "01/18/2021",
      reported_issue:
        "No of people have answered they have cough but not fever",
    },
    {
      date: "01/19/2021",
      reported_issue: "No of people have not taken test today",
    },
  ],
  employees: [
    {
      date: "01/01/2021",
      employee_id: "001",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "1.00%",
    },
    {
      date: "01/02/2021",
      employee_id: "002",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "2.00%",
    },
    {
      date: "01/03/2021",
      employee_id: "003",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "3.20%",
    },
    {
      date: "01/04/2021",
      employee_id: "004",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "1.20%",
    },
    {
      date: "01/05/2021",
      employee_id: "005",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "0.50%",
    },
    {
      date: "01/06/2021",
      employee_id: "006",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "0.40%",
    },
    {
      date: "01/07/2021",
      employee_id: "007",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "1.20%",
    },
    {
      date: "01/08/2021",
      employee_id: "008",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "1.50%",
    },
    {
      date: "01/09/2021",
      employee_id: "009",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "2.23%",
    },
    {
      date: "01/10/2021",
      employee_id: "010",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "4.50%",
    },
    {
      date: "01/11/2021",
      employee_id: "011",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "3.30%",
    },
    {
      date: "01/12/2021",
      employee_id: "012",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "1.20%",
    },
    {
      date: "01/13/2021",
      employee_id: "013",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "5.30%",
    },
    {
      date: "01/14/2021",
      employee_id: "014",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "3.20%",
    },
    {
      date: "01/15/2021",
      employee_id: "015",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "4.00%",
    },
    {
      date: "01/16/2021",
      employee_id: "016",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "2.10%",
    },
    {
      date: "01/17/2021",
      employee_id: "017",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "2.30%",
    },
    {
      date: "01/18/2021",
      employee_id: "018",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "3.50%",
    },
    {
      date: "01/19/2021",
      employee_id: "019",
      working_hrs: 8,
      agreed_man_hrs: 7,
      absenteesim_rate: "2.10%",
    },
  ],
};

export default data;
